// Generated by CoffeeScript 1.10.0
(function() {
  (function($) {
    var AudioController, root;
    AudioController = (function() {
      function AudioController() {}

      AudioController.prototype.context = new (window.AudioContext || window.webkitAudioContext)();

      AudioController.prototype.bufferMap = {};

      AudioController.prototype.add = function(name, soundUrl) {
        var req;
        req = new XMLHttpRequest();
        req.open("GET", soundUrl, true);
        req.responseType = "arraybuffer";
        req.onload = (function(_this) {
          return function() {
            return _this.context.decodeAudioData(req.response, function(buffer) {
              if (buffer != null) {
                return _this.bufferMap[name] = buffer;
              } else {
                return console.error("cannot decode " + soundUrl);
              }
            });
          };
        })(this);
        return req.send();
      };

      AudioController.prototype.play = function(name) {
        var src;
        src = this.context.createBufferSource();
        console.log(this.bufferMap);
        src.buffer = this.bufferMap[name];
        src.connect(this.context.destination);
        return src.noteOn(0);
      };

      return AudioController;

    })();
    root = typeof exports !== "undefined" && exports !== null ? exports : this;
    return root.AudioController = AudioController;
  })(jQuery);

}).call(this);

//# sourceMappingURL=audio-api.js.map
